In [1]:
import math, copy
import numpy as np

from classNeuron import Neuron
from classNetwork import Network
import numpy as np
from classGame2048 import Game2048
import math
import tkinter as tk
import time
import pickle
import concurrent.futures
from utils import *

In [2]:
mygame = Game2048(4)
mygame.generate_tile()
mygame.generate_tile()
mygame.show_state()
print('====================')
mygame.swipe('right')
mygame.show_state()
print('--------------------')
print(mygame.get_state(True))
print('--------------------')
print(mygame.get_score())

[[0. 0. 0. 0.]
 [4. 0. 4. 0.]
 [0. 0. 0. 2.]
 [0. 2. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 8.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]]
--------------------
[0. 0. 0. 0. 0. 0. 0. 8. 0. 0. 2. 2. 0. 0. 0. 2.]
--------------------
94.0


### Check Neuron class

In [3]:
n = Neuron(np.array([-100, -100]), -100000)
print(n.forward(np.array([25600000, 25600000])))

-1.0


### Check Network 

In [4]:
X1 = np.array([[1], [4], [2], [-4]])
X2 = np.array([[1, 2, 3,-3], [5,-20,12,0.26]])
b1 = np.array([1,1,1,1])
b2 = np.array([1,1])
N = Network([X1,X2],[b1,b2])
I = np.array([1,0.3,-1,3])
print(N.evaluate(I))

[ 0.99980999 -1.        ]


In [27]:
from classGeneticLearner import GeneticLearner

fname = './models/model_'
n_agents = 1000
generations_per_batch = 1
n_batches = 10
total_generations = generations_per_batch * n_batches
print('Preparing to run ' + str(total_generations) +' generations...')

G = GeneticLearner(n_agents,[16,8,4],seed = 4)
for i in range(n_batches):
    print("Starting batch " + str(i))
    G.run_n_generations(generations_per_batch)
    gen_num = i * generations_per_batch
    save_model_state(G, fname + str(gen_num) + '.p')
    print("Model " + str(gen_num) + " Saved")


Preparing to run 10 generations...
Starting batch 0
Generation 0 - maximum: 436.0  median: 96.0 minimum: 24.0
Model 0 Saved
Starting batch 1
Generation 0 - maximum: 768.0  median: 92.0 minimum: 24.0
Model 1 Saved
Starting batch 2
Generation 0 - maximum: 748.0  median: 96.0 minimum: 24.0
Model 2 Saved
Starting batch 3
Generation 0 - maximum: 1618.0  median: 98.0 minimum: 24.0
Model 3 Saved
Starting batch 4
Generation 0 - maximum: 448.0  median: 98.0 minimum: 24.0
Model 4 Saved
Starting batch 5
Generation 0 - maximum: 458.0  median: 100.0 minimum: 24.0
Model 5 Saved
Starting batch 6
Generation 0 - maximum: 826.0  median: 100.0 minimum: 24.0
Model 6 Saved
Starting batch 7
Generation 0 - maximum: 824.0  median: 100.0 minimum: 24.0
Model 7 Saved
Starting batch 8
Generation 0 - maximum: 804.0  median: 100.0 minimum: 24.0
Model 8 Saved
Starting batch 9
Generation 0 - maximum: 862.0  median: 104.0 minimum: 24.0
Model 9 Saved


### Conitnue training

In [ ]:
from classGeneticLearner import GeneticLearner
fname = 'models/model_'
gen_to_load = 193
generations_per_batch = 1
n_batches = 1000
total_generations = generations_per_batch * n_batches
full_filename = fname+str(gen_to_load)+'.p'
print('Loading ' + full_filename + ' and running ' + str(total_generations) + ' more generations')
try:
    G = load_model_state(full_filename)
except:
    raise ValueError('File does not exist: ' + full_filename)
for i in range(n_batches):
    print("Starting batch "+str(i))
    G.run_n_generations(generations_per_batch)
    gen_num = (1+i)*generations_per_batch + gen_to_load
    save_model_state(G,fname + str(gen_num) + '.p')
    print("Model " + str(gen_num) + " Saved")



Loading models/model_193.p and running 1000 more generations
Starting batch 0
Generation 0 - maximum: 1606.0  median: 444.0 minimum: 24.0
Model 194 Saved
Starting batch 1
Generation 0 - maximum: 1584.0  median: 452.0 minimum: 24.0
Model 195 Saved
Starting batch 2
Generation 0 - maximum: 1594.0  median: 444.0 minimum: 24.0
Model 196 Saved
Starting batch 3
Generation 0 - maximum: 1634.0  median: 444.0 minimum: 24.0
Model 197 Saved
Starting batch 4
Generation 0 - maximum: 1586.0  median: 444.0 minimum: 24.0
Model 198 Saved
Starting batch 5
Generation 0 - maximum: 2912.0  median: 450.0 minimum: 24.0
Model 199 Saved
Starting batch 6
Generation 0 - maximum: 1612.0  median: 450.0 minimum: 24.0
Model 200 Saved
Starting batch 7
Generation 0 - maximum: 1608.0  median: 450.0 minimum: 24.0
Model 201 Saved
Starting batch 8
Generation 0 - maximum: 2950.0  median: 451.0 minimum: 24.0
Model 202 Saved
Starting batch 9
Generation 0 - maximum: 2946.0  median: 455.0 minimum: 24.0
Model 203 Saved
Starting 

Model 280 Saved
Starting batch 87
Generation 0 - maximum: 2992.0  median: 806.0 minimum: 24.0
Model 281 Saved
Starting batch 88
Generation 0 - maximum: 3002.0  median: 798.0 minimum: 24.0
Model 282 Saved
Starting batch 89
Generation 0 - maximum: 2984.0  median: 802.0 minimum: 24.0
Model 283 Saved
Starting batch 90
Generation 0 - maximum: 2982.0  median: 802.0 minimum: 24.0
Model 284 Saved
Starting batch 91
Generation 0 - maximum: 3044.0  median: 800.0 minimum: 24.0
Model 285 Saved
Starting batch 92
Generation 0 - maximum: 3044.0  median: 802.0 minimum: 24.0
Model 286 Saved
Starting batch 93
Generation 0 - maximum: 3030.0  median: 802.0 minimum: 24.0
Model 287 Saved
Starting batch 94
Generation 0 - maximum: 2996.0  median: 800.0 minimum: 24.0
Model 288 Saved
Starting batch 95
Generation 0 - maximum: 2980.0  median: 806.0 minimum: 24.0
Model 289 Saved
Starting batch 96
Generation 0 - maximum: 3046.0  median: 800.0 minimum: 24.0
Model 290 Saved
Starting batch 97
Generation 0 - maximum: 29

### Testing

In [ ]:
fname = 'models/model_'
n_new_games = 2
G = load_model_state(fname + '.p')
A = G.get_best_agent()
root = tk.Tk()
root.title("2048 Game")
score,win = A.replay_previous_game(root)
print('Agent score: '+str(score)+' Win status: '+ str(win))
time.sleep(0.5)
for i in range(n_new_games):
    score, win = A.play_game(root)
    print('Agent score: ' + str(score) + ' Win status: ' + str(win))
    time.sleep(0.5)

input("Press Enter to end...")