In [15]:
import math, copy
import numpy as np

from classNeuron import Neuron
from classNetwork import Network
import numpy as np
from classGame2048 import Game2048
import math
# import classGame2048 as classGame2048
import tkinter as tk
import time
import pickle
import concurrent.futures


In [16]:
mygame = Game2048(4)
mygame.generate_tile()
mygame.generate_tile()
mygame.show_state()
print('====================')
mygame.swipe('right')
mygame.show_state()
print('--------------------')
print(mygame.get_state(True))
print('--------------------')
print(mygame.get_score())

[[0. 4. 0. 0.]
 [0. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 4. 4. 0.]]
[[0. 0. 0. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]
 [0. 4. 0. 8.]]
--------------------
[0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 2. 0. 4. 0. 8.]
--------------------
98.0


### Check Neuron class

In [17]:
n = Neuron(np.array([-100, -100]), -100000)
print(n.forward(np.array([25600000, 25600000])))

-1.0


### Check Network 

In [18]:
X1 = np.array([[1], [4], [2], [-4]])
X2 = np.array([[1, 2, 3,-3], [5,-20,12,0.26]])
b1 = np.array([1,1,1,1])
b2 = np.array([1,1])
N = Network([X1,X2],[b1,b2])
I = np.array([1,0.3,-1,3])
print(N.evaluate(I))

[ 0.99980999 -1.        ]
